### ISSUE TITLE
Feature request: `/exec` command

### ISSUE THREAD

**Issue by C0DK** [Rudi9719/kbtui#10]
as the system currently doesn't have all the features the keybase CLI has - it'd be nice to be able to run keybase features directly from the TUI.. so forinstance writing `/exec follow haukened` would equal running `keybase follow haukened` - this would make a lot of things possible within the TUI without us having to work on implementing them (we can also implement them later on)

**Comment by ghost** [comment]
@C0DK 

this is a nice feature as long as it's constrained to `keybase` namespacing and nothing drops to system.

**Comment by C0DK** [comment]
sure. some sort of input sanitization is required :)

**Comment by haukened** [comment]
I'm flattered that you would follow me, even as an example

**Comment by C0DK** [comment]
I've always said "follow by example"

**Comment by Rudi9719** [comment]
https://godoc.org/samhofi.us/x/keybase#Keybase.Exec

This might be relevant/useful
