### ISSUE TITLE
Config TOML file

### ISSUE THREAD

**Issue by Rudi9719** [Rudi9719/kbtui#17]
Configuration via TOML file instead of compiled userConfig.go

**Comment by Rudi9719** [comment]
Waiting on input from @C0DK for colours, and then potentially changing how configs are stored (Auto-populate file if it doesn't exist?)

**Comment by C0DK** [comment]
So i was thinking maybe having something like if `~/.config/kbtui.tml` exists - load that- otherwise  pick the one in the package-dir (which we verify with travis that works) which can be used as a template.
