### ISSUE TITLE
Colour upgrades

### ISSUE THREAD

**Issue by Rudi9719** [Rudi9719/kbtui#18]
Upgrades to colour system for customization and stability across various platforms

**Comment by C0DK** [comment]
Can you assign me, somehow? :)

**Comment by Rudi9719** [comment]
@C0DK moving forward with colours, could you expose either a string or int of some sort for me to implement in the configs? The quote below is from the [TOML repo](https://github.com/toml-lang/toml) expressing the valid datatypes. Looking at how you previously handled colours this should be easy to do (and possibly already done)

> Values must be of the following types: String, Integer, Float, Boolean, Datetime, Array, or Inline Table. Unspecified values are invalid.

Thanks,
Rudi

**Comment by C0DK** [comment]
will do! :)

**Comment by Rudi9719** [comment]
If you check out the latest commit I pushed referencing #17 I added the basic structure for the config file. I'll be working on filling/ignoring empty or missing values in the tml, but I was thinking for colours it might make sense to have `colorless` in the Basics, then have the color settings in a separate `Colors` section. What do you think?

**Comment by Rudi9719** [comment]
This is being addressed by PR #28
